name: node_preamble
author: Michael Bullington <mikebullingtn@gmail.com>
homepage: https://github.com/mbullington/node_preamble.dart
version: 2.0.2
description: Better node.js preamble for dart2js, use it in your build system.

environment:
  sdk: '>=3.8.0 <4.0.0'
