name: e2e_interop_test
description: End-to-end test for node interop and builders
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dev_dependencies:
  test: ^1.26.2
  build_runner: ^2.4.14
  build_node_compilers:
    path: ../build_node_compilers
  js_interop: ^0.0.1
  node_interop:
    path: ../node_interop

dependency_overrides:
  node_preamble:
    path: ../node_preamble
