name: build_node_compilers
version: 0.3.2
description: Builders wrapping DDC and dart2js compilers configured to output Node modules.
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  analyzer: ^7.4.5
  bazel_worker: ^1.1.3
  build: '^2.4.2'
  build_config: '^1.1.2'
  build_modules: ^5.0.13
  collection: ^1.0.0
  crypto: ^3.0.6
  logging: ^1.3.0
  meta: ^1.1.0
  node_preamble: ^1.4.8
  path: ^1.4.2
  pool: ^1.3.6
  scratch_space: ^1.0.2

dev_dependencies:
  build_test: ^2.2.3
  pedantic: ^1.0.0
  test: ^1.26.2
  a:
    path: test/fixtures/a
  b:
    path: test/fixtures/b

dependency_overrides: 
  node_preamble:
    path: ../node_preamble
