name: node_http
description: HTTP client powered by Node.js I/O system.
version: 1.0.1
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  http: ^0.12.0
  node_interop: ^1.0.0
  node_io: ^1.0.0

dev_dependencies:
  build_runner: ">=1.10.0 <1.10.2"
  build_node_compilers:
    path: ../build_node_compilers
  build_test: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.26.2
